### ISSUE TITLE
Readme problem github

### ISSUE THREAD

**Issue by kimia-allami** [kimia-allami/Readme#2]
Why my readme doesn’t appear in my profile github?

**Comment by zeusssz** [comment]
the issue is that this is not your `kimia-allami/kimia-allami` root repository. the readme.md must be in that repository for it to show up on your profile

**Comment by amirallami-code** [comment]
To display your README file on your GitHub profile, you can follow these steps:

1. **Create a new repository**: Go to your GitHub account and create a new repository. The name of the repository should be the same as your GitHub username, for example, if your username is "johndoe", the repository name should be "johndoe".

2. **Add your README file**: In the root directory of your newly created repository, create a file named `README.md`. This is where you will add the content for your profile README.

3. **Customize your README**: You can use Markdown syntax to format your README file. Some common elements you might want to include are:
   - An introduction about yourself
   - Your skills and technologies
   - Your projects and portfolio
   - Social media and contact information
   - Badges (e.g., GitHub stats, licenses)

Here's an example of what your `README.md` file might look like:

```markdown
# Hello, I'm John Doe 👋

I'm a Frontend Developer with a passion for creating intuitive and responsive web applications.

## Skills 🛠️

- HTML, CSS, JavaScript
- React.js, Vue.js
- Responsive Design
- Git and GitHub

## Projects 🚀

- [Personal Portfolio](https://johndoe.com)
- [Todo App](https://github.com/johndoe/todo-app)
- [Weather App](https://github.com/johndoe/weather-app)

## Connect with me 📫

- Twitter: [@johndoe](https://twitter.com/johndoe)
- LinkedIn: [johndoe](https://linkedin.com/in/johndoe)
- Email: johndoe@example.com

![GitHub stats](https://github-readme-stats.vercel.app/api?username=johndoe&show_icons=true&theme=radical)
```

4. **Commit and push your changes**: After creating and customizing your `README.md` file, commit your changes and push them to the repository.

5. **View your profile README**: Your profile README will now be visible on your GitHub profile page. You can access it by going to `https://github.com/your-username`.

That's it! Your GitHub profile README is now set up and visible to anyone who visits your GitHub profile. Remember, you can continue to update and customize your README file as needed.

**Comment by kimia-allami** [comment]
Oh, then it appears in my profile?

**Comment by kimia-allami** [comment]
Oh so then it appears in my profile?

**Comment by amirallami-code** [comment]
> Oh so then it appears in my profile?

Yes absolutely

**Comment by amirallami-code** [comment]
> > > Oh so then it appears in my profile?
> > 
> > 
> > Yes absolutely
> 
> Thanks so much

Your welcome
