### ISSUE TITLE
No i can’t unfortunately

### ISSUE THREAD

**Issue by kimia-allami** [kimia-allami/Readme#3]
No i can’t unfortunately

_Originally posted by @kimia-allami in https://github.com/kimia-allami/Readme/discussions/1#discussioncomment-10521708_

**Comment by amirallami-code** [comment]
> No i can’t unfortunately
> 
> _Originally posted by @kimia-allami in [#1 (comment)](https://github.com/kimia-allami/Readme/discussions/1#discussioncomment-10521708)_

I just send you what would you do in previous issue, check that out!
